--- 
title: anndataToGiotto 
format: rst 
date: 2023-01-19 
--- 
# `anndataToGiotto`

Convert anndata to Giotto


## Description

Converts a spatial anndata (e.g. scanpy) .h5ad file into a Giotto object


## Usage

```r
anndataToGiotto(
  anndata_path = NULL,
  n_key_added = NULL,
  spatial_key_added = NULL,
  spat_unit = NULL,
  feat_type = NULL,
  python_path = NULL
)
```


## Arguments

Argument      |Description
------------- |----------------
`anndata_path`     |     path to the .h5ad file
`n_key_added`     |     equivalent of "key_added" argument from scanpy.pp.neighbors(). Cannot be "spatial". This becomes the name of the nearest network in the gobject.
`spat_unit`     |     desired spatial unit for conversion, default NULL
`feat_type`     |     desired feature type for conversion, default NULL
`python_path`     |     path to python executable within a conda/miniconda environment


## Details

Function in beta. Converts a .h5ad file into a Giotto object.
 The returned Giotto Object will take default insructions with the
 exception of the python path, which may be customized.
 See [`changeGiottoInstructions`](#changegiottoinstructions) to modify instructions after creation.


## Value

Giotto object


