--- 
title: get_spatialNetwork 
format: rst 
date: 2023-01-19 
--- 
# `get_spatialNetwork`

Get spatial network


## Description

Function to get a spatial network


## Usage

```r
get_spatialNetwork(
  gobject,
  spat_unit = NULL,
  name = NULL,
  output = c("spatialNetworkObj", "networkDT", "networkDT_before_filter", "outputObj"),
  set_defaults = TRUE
)
```


## Arguments

Argument      |Description
------------- |----------------
`gobject`     |     giotto object
`spat_unit`     |     spatial unit (e.g. "cell")
`name`     |     name of spatial network
`output`     |     object type to return as. Options: 'spatialNetworkObj' (default), 'networkDT' and 'networkDT_before_filter' for data.table outputs.
`set_defaults`     |     set default spat_unit and feat_type. Change to FALSE only when


## Seealso

Other spatial network data accessor functions:
 [`set_spatialNetwork`](#setspatialnetwork) 
 
 Other functions to get data from giotto object:
 [`get_NearestNetwork`](#getnearestnetwork) ,
 [`get_dimReduction`](#getdimreduction) ,
 [`get_expression_values`](#getexpressionvalues) ,
 [`get_feature_info`](#getfeatureinfo) ,
 [`get_giottoImage`](#getgiottoimage) ,
 [`get_multiomics`](#getmultiomics) ,
 [`get_polygon_info`](#getpolygoninfo) ,
 [`get_spatialGrid`](#getspatialgrid) ,
 [`get_spatial_enrichment`](#getspatialenrichment) ,
 [`get_spatial_locations`](#getspatiallocations)


