--- 
title: get_polygon_info 
format: rst 
date: 2023-01-19 
--- 
# `get_polygon_info`

Get polygon info


## Description

Get giotto polygon spatVector


## Usage

```r
get_polygon_info(
  gobject,
  polygon_name = NULL,
  polygon_overlap = NULL,
  return_giottoPolygon = FALSE
)
```


## Arguments

Argument      |Description
------------- |----------------
`gobject`     |     giotto object
`polygon_name`     |     name of polygons. Default "cell"
`polygon_overlap`     |     include polygon overlap information
`return_giottoPolygon`     |     (Defaults to FALSE) Return as giottoPolygon S4 object


## Seealso

Other polygon info data accessor functions:
 [`set_polygon_info`](#setpolygoninfo) 
 
 Other functions to get data from giotto object:
 [`get_NearestNetwork`](#getnearestnetwork) ,
 [`get_dimReduction`](#getdimreduction) ,
 [`get_expression_values`](#getexpressionvalues) ,
 [`get_feature_info`](#getfeatureinfo) ,
 [`get_giottoImage`](#getgiottoimage) ,
 [`get_multiomics`](#getmultiomics) ,
 [`get_spatialGrid`](#getspatialgrid) ,
 [`get_spatialNetwork`](#getspatialnetwork) ,
 [`get_spatial_enrichment`](#getspatialenrichment) ,
 [`get_spatial_locations`](#getspatiallocations)


