--- 
title: get_feature_info 
format: rst 
date: 2023-01-19 
--- 
# `get_feature_info`

Get feature info


## Description

Get giotto points spatVector


## Usage

```r
get_feature_info(gobject, feat_type = NULL, set_defaults = TRUE)
```


## Arguments

Argument      |Description
------------- |----------------
`gobject`     |     giotto object
`feat_type`     |     feature type (e.g. "rna", "dna", "protein")
`set_defaults`     |     set default spat_unit and feat_type. Change to FALSE only when


## Seealso

Other feature info data accessor functions:
 [`set_feature_info`](#setfeatureinfo) 
 
 Other functions to get data from giotto object:
 [`get_NearestNetwork`](#getnearestnetwork) ,
 [`get_dimReduction`](#getdimreduction) ,
 [`get_expression_values`](#getexpressionvalues) ,
 [`get_giottoImage`](#getgiottoimage) ,
 [`get_multiomics`](#getmultiomics) ,
 [`get_polygon_info`](#getpolygoninfo) ,
 [`get_spatialGrid`](#getspatialgrid) ,
 [`get_spatialNetwork`](#getspatialnetwork) ,
 [`get_spatial_enrichment`](#getspatialenrichment) ,
 [`get_spatial_locations`](#getspatiallocations)


