--- 
title: get_expression_values 
format: rst 
date: 2023-01-19 
--- 
# `get_expression_values`

Get expression values


## Description

Function to get expression values from giotto object


## Usage

```r
get_expression_values(
  gobject,
  values = NULL,
  spat_unit = NULL,
  feat_type = NULL,
  output = c("exprObj", "matrix"),
  set_defaults = TRUE
)
```


## Arguments

Argument      |Description
------------- |----------------
`gobject`     |     giotto object
`values`     |     expression values to extract (e.g. "raw", "normalized", "scaled")
`spat_unit`     |     spatial unit (e.g. "cell")
`feat_type`     |     feature type (e.g. "rna", "dna", "protein")
`output`     |     what object type to retrieve the expression as. Currently either 'matrix' for the matrix object contained in the exprObj or 'exprObj' (default) for the exprObj itself are allowed.
`set_defaults`     |     set default spat_unit and feat_type. Change to FALSE only when


## Value

expression matrix


## Seealso

Other expression accessor functions:
 [`set_expression_values`](#setexpressionvalues) 
 
 Other functions to get data from giotto object:
 [`get_NearestNetwork`](#getnearestnetwork) ,
 [`get_dimReduction`](#getdimreduction) ,
 [`get_feature_info`](#getfeatureinfo) ,
 [`get_giottoImage`](#getgiottoimage) ,
 [`get_multiomics`](#getmultiomics) ,
 [`get_polygon_info`](#getpolygoninfo) ,
 [`get_spatialGrid`](#getspatialgrid) ,
 [`get_spatialNetwork`](#getspatialnetwork) ,
 [`get_spatial_enrichment`](#getspatialenrichment) ,
 [`get_spatial_locations`](#getspatiallocations)


