--- 
title: get_dimReduction 
format: rst 
date: 2023-01-19 
--- 
# `get_dimReduction`

Get dimension reduction


## Description

Function to get a dimension reduction object


## Usage

```r
get_dimReduction(
  gobject,
  spat_unit = NULL,
  feat_type = NULL,
  reduction = c("cells", "feats"),
  reduction_method = c("pca", "umap", "tsne"),
  name = "pca",
  output = c("dimObj", "data.table"),
  set_defaults = TRUE
)
```


## Arguments

Argument      |Description
------------- |----------------
`gobject`     |     giotto object
`spat_unit`     |     spatial unit (e.g. "cell")
`feat_type`     |     feature type (e.g. "rna", "dna", "protein")
`reduction`     |     reduction on cells or features (e.g. "cells", "feats")
`reduction_method`     |     reduction method (e.g. "pca", "umap", "tsne")
`name`     |     name of reduction results
`output`     |     object type to return as. Either 'dimObj' (default) or 'data.table of the embedding coordinates.
`set_defaults`     |     set default spat_unit and feat_type. Change to FALSE only when


## Value

dim reduction object (default) or dim reduction coordinates


## Seealso

Other dimensional reduction data accessor functions:
 [`set_dimReduction`](#setdimreduction) 
 
 Other functions to get data from giotto object:
 [`get_NearestNetwork`](#getnearestnetwork) ,
 [`get_expression_values`](#getexpressionvalues) ,
 [`get_feature_info`](#getfeatureinfo) ,
 [`get_giottoImage`](#getgiottoimage) ,
 [`get_multiomics`](#getmultiomics) ,
 [`get_polygon_info`](#getpolygoninfo) ,
 [`get_spatialGrid`](#getspatialgrid) ,
 [`get_spatialNetwork`](#getspatialnetwork) ,
 [`get_spatial_enrichment`](#getspatialenrichment) ,
 [`get_spatial_locations`](#getspatiallocations)


