--- 
title: get_spatialGrid 
format: rst 
date: 2023-01-19 
--- 
# `get_spatialGrid`

Get spatial grid


## Description

Function to get spatial grid


## Usage

```r
get_spatialGrid(
  gobject,
  spat_unit = NULL,
  feat_type = NULL,
  name = NULL,
  return_grid_Obj = FALSE,
  set_defaults = TRUE
)
```


## Arguments

Argument      |Description
------------- |----------------
`gobject`     |     giotto object
`spat_unit`     |     spatial unit (e.g. "cell")
`feat_type`     |     feature type (e.g. "rna", "dna", "protein")
`name`     |     name of spatial grid
`return_grid_Obj`     |     return grid object (default = FALSE)
`set_defaults`     |     set default spat_unit and feat_type. Change to FALSE only when


## Seealso

Other spatial grid data accessor functions:
 [`set_spatialGrid`](#setspatialgrid) 
 
 Other functions to get data from giotto object:
 [`get_NearestNetwork`](#getnearestnetwork) ,
 [`get_dimReduction`](#getdimreduction) ,
 [`get_expression_values`](#getexpressionvalues) ,
 [`get_feature_info`](#getfeatureinfo) ,
 [`get_giottoImage`](#getgiottoimage) ,
 [`get_multiomics`](#getmultiomics) ,
 [`get_polygon_info`](#getpolygoninfo) ,
 [`get_spatialNetwork`](#getspatialnetwork) ,
 [`get_spatial_enrichment`](#getspatialenrichment) ,
 [`get_spatial_locations`](#getspatiallocations)


