--- 
title: plotInteractionChangedGenes 
format: rst 
date: 2023-01-19 
--- 
# `plotInteractionChangedGenes`

Plot interaction changed genes


## Description

Create barplot to visualize interaction changed features


## Usage

```r
plotInteractionChangedGenes(...)
```


## Arguments

Argument      |Description
------------- |----------------
`...`     |      Arguments passed on to [`plotInteractionChangedFeats`](#plotinteractionchangedfeats)   list("\n", "    ", list(list(list("gobject")), list("giotto object")), "\n", "    ", list(list(list("icfObject")), list("ICF (interaction changed feature) score object")), "\n", "    ", list(list(list("source_type")), list("cell type of the source cell")), "\n", "    ", list(list(list("source_markers")), list("markers for the source cell type")), "\n", "    ", list(list(list("ICF_feats")), list("named character vector of ICF features")), "\n", "    ", list(list(list("cell_color_code")), list("cell color code for the interacting cell types")), 
    "\n", "    ", list(list(list("show_plot")), list("show plots")), "\n", "    ", list(list(list("return_plot")), list("return plotting object")), "\n", "    ", list(list(list("save_plot")), list("directly save the plot [boolean]")), "\n", "    ", list(list(list("save_param")), list("list of saving parameters from ", list(list("all_plots_save_function")))), "\n", "    ", list(list(list("default_save_name")), list("default save name for saving, don't change, change save_name in save_param")), "\n", 
    "  ")


## Seealso

[`plotInteractionChangedFeats`](#plotinteractionchangedfeats)


