--- 
title: select_dimReduction 
format: rst 
date: 2023-01-19 
--- 
# `select_dimReduction`

select_dimReduction


## Description

select_dimReduction


## Usage

```r
select_dimReduction(...)
```


## Arguments

Argument      |Description
------------- |----------------
`...`     |      Arguments passed on to [`get_dimReduction`](#getdimreduction)   list("\n", "    ", list(list(list("reduction")), list("reduction on cells or features (e.g. \"cells\", \"feats\")")), "\n", "    ", list(list(list("reduction_method")), list("reduction method (e.g. \"pca\", \"umap\", \"tsne\")")), "\n", "    ", list(list(list("name")), list("name of reduction results")), "\n", "    ", list(list(list("output")), list("object type to return as. Either 'dimObj' (default) or 'data.table\n", "of the embedding coordinates.")), "\n", "    ", list(list(list("gobject")), 
    list("giotto object")), "\n", "    ", list(list(list("spat_unit")), list("spatial unit (e.g. \"cell\")")), "\n", "    ", list(list(list("feat_type")), list("feature type (e.g. \"rna\", \"dna\", \"protein\")")), "\n", "    ", list(list(list("set_defaults")), list("set default spat_unit and feat_type. Change to FALSE only when")), "\n", "  ")


## Seealso

[`get_dimReduction`](#getdimreduction)


