--- 
title: set_feature_info 
format: rst 
date: 2023-01-19 
--- 
# `set_feature_info`

Set feature info


## Description

Set giotto polygon spatVector for features


## Usage

```r
set_feature_info(gobject, feat_type = NULL, gpolygon, verbose = TRUE)
```


## Arguments

Argument      |Description
------------- |----------------
`gobject`     |     giotto object
`feat_type`     |     feature type (e.g. "rna", "dna", "protein")
`gpolygon`     |     giotto polygon
`verbose`     |     be verbose


## Value

giotto object


## Seealso

Other feature info data accessor functions:
 [`get_feature_info`](#getfeatureinfo) 
 
 Other functions to set data in giotto object:
 [`get_cell_id`](#getcellid) ,
 [`get_feat_id`](#getfeatid) ,
 [`set_NearestNetwork`](#setnearestnetwork) ,
 [`set_cell_id`](#setcellid) ,
 [`set_cell_metadata`](#setcellmetadata) ,
 [`set_dimReduction`](#setdimreduction) ,
 [`set_expression_values`](#setexpressionvalues) ,
 [`set_feat_id`](#setfeatid) ,
 [`set_feature_metadata`](#setfeaturemetadata) ,
 [`set_giottoImage`](#setgiottoimage) ,
 [`set_multiomics`](#setmultiomics) ,
 [`set_polygon_info`](#setpolygoninfo) ,
 [`set_spatialGrid`](#setspatialgrid) ,
 [`set_spatialNetwork`](#setspatialnetwork) ,
 [`set_spatial_enrichment`](#setspatialenrichment) ,
 [`set_spatial_locations`](#setspatiallocations)


