--- 
title: set_multiomics 
format: rst 
date: 2023-01-19 
--- 
# `set_multiomics`

Set multiomics integration results


## Description

Set a multiomics integration result in a Giotto object


## Usage

```r
set_multiomics(
  gobject,
  result,
  spat_unit = NULL,
  feat_type = NULL,
  integration_method = "WNN",
  result_name = "theta_weighted_matrix",
  verbose = TRUE
)
```


## Arguments

Argument      |Description
------------- |----------------
`gobject`     |     A Giotto object
`result`     |     A matrix or result from multiomics integration (e.g. theta weighted values from runWNN)
`spat_unit`     |     spatial unit (e.g. 'cell')
`feat_type`     |     (e.g. 'rna_protein')
`integration_method`     |     multiomics integration method used. Default = 'WNN'
`result_name`     |     Default = 'theta_weighted_matrix'
`verbose`     |     be verbose


## Value

A giotto object


## Seealso

Other multiomics accessor functions:
 [`get_multiomics`](#getmultiomics) 
 
 Other functions to set data in giotto object:
 [`get_cell_id`](#getcellid) ,
 [`get_feat_id`](#getfeatid) ,
 [`set_NearestNetwork`](#setnearestnetwork) ,
 [`set_cell_id`](#setcellid) ,
 [`set_cell_metadata`](#setcellmetadata) ,
 [`set_dimReduction`](#setdimreduction) ,
 [`set_expression_values`](#setexpressionvalues) ,
 [`set_feat_id`](#setfeatid) ,
 [`set_feature_info`](#setfeatureinfo) ,
 [`set_feature_metadata`](#setfeaturemetadata) ,
 [`set_giottoImage`](#setgiottoimage) ,
 [`set_polygon_info`](#setpolygoninfo) ,
 [`set_spatialGrid`](#setspatialgrid) ,
 [`set_spatialNetwork`](#setspatialnetwork) ,
 [`set_spatial_enrichment`](#setspatialenrichment) ,
 [`set_spatial_locations`](#setspatiallocations)


