--- 
title: set_NearestNetwork 
format: rst 
date: 2023-01-19 
--- 
# `set_NearestNetwork`

Set nearest network


## Description

Set a NN-network for a Giotto object


## Usage

```r
set_NearestNetwork(
  gobject,
  nn_network,
  spat_unit = NULL,
  feat_type = NULL,
  nn_network_to_use = "sNN",
  network_name = "sNN.pca",
  provenance = NULL,
  verbose = TRUE,
  set_defaults = TRUE
)
```


## Arguments

Argument      |Description
------------- |----------------
`gobject`     |     giotto object
`nn_network`     |     nnNetObj or igraph nearest network object. Data.table not yet supported.
`spat_unit`     |     spatial unit (e.g. "cell")
`feat_type`     |     feature type (e.g. "rna", "dna", "protein")
`nn_network_to_use`     |     "kNN" or "sNN"
`network_name`     |     name of NN network to be used
`provenance`     |     provenance information (optional)
`verbose`     |     be verbose
`set_defaults`     |     set default spat_unit and feat_type. Change to FALSE only when


## Value

giotto object


## Seealso

Other expression space nearest network accessor functions:
 [`get_NearestNetwork`](#getnearestnetwork) 
 
 Other functions to set data in giotto object:
 [`get_cell_id`](#getcellid) ,
 [`get_feat_id`](#getfeatid) ,
 [`set_cell_id`](#setcellid) ,
 [`set_cell_metadata`](#setcellmetadata) ,
 [`set_dimReduction`](#setdimreduction) ,
 [`set_expression_values`](#setexpressionvalues) ,
 [`set_feat_id`](#setfeatid) ,
 [`set_feature_info`](#setfeatureinfo) ,
 [`set_feature_metadata`](#setfeaturemetadata) ,
 [`set_giottoImage`](#setgiottoimage) ,
 [`set_multiomics`](#setmultiomics) ,
 [`set_polygon_info`](#setpolygoninfo) ,
 [`set_spatialGrid`](#setspatialgrid) ,
 [`set_spatialNetwork`](#setspatialnetwork) ,
 [`set_spatial_enrichment`](#setspatialenrichment) ,
 [`set_spatial_locations`](#setspatiallocations)


