--- 
title: set_feat_id 
format: rst 
date: 2023-01-19 
--- 
# `set_feat_id`

Set feat IDs for a given feature type


## Description

Across a single modality/feature type, all feature information is
 expected to share a single set of feat_IDs. These feat_IDs are stored within
 the giotto object's `feat_ID` slot. Getters and setters for this slot
 directly (get) or replace (set) this slot.


## Usage

```r
set_feat_id(gobject, feat_type = NULL, feat_IDs, set_defaults = TRUE)
```


## Arguments

Argument      |Description
------------- |----------------
`gobject`     |     giotto object
`feat_type`     |     feature type (e.g. "rna", "dna", "protein")
`set_defaults`     |     set default spat_unit and feat_type. Change to FALSE only when


## Value

giotto object with set cell_ID slot


## Seealso

get_feat_id
 
 Other functions to set data in giotto object:
 [`get_cell_id`](#getcellid) ,
 [`get_feat_id`](#getfeatid) ,
 [`set_NearestNetwork`](#setnearestnetwork) ,
 [`set_cell_id`](#setcellid) ,
 [`set_cell_metadata`](#setcellmetadata) ,
 [`set_dimReduction`](#setdimreduction) ,
 [`set_expression_values`](#setexpressionvalues) ,
 [`set_feature_info`](#setfeatureinfo) ,
 [`set_feature_metadata`](#setfeaturemetadata) ,
 [`set_giottoImage`](#setgiottoimage) ,
 [`set_multiomics`](#setmultiomics) ,
 [`set_polygon_info`](#setpolygoninfo) ,
 [`set_spatialGrid`](#setspatialgrid) ,
 [`set_spatialNetwork`](#setspatialnetwork) ,
 [`set_spatial_enrichment`](#setspatialenrichment) ,
 [`set_spatial_locations`](#setspatiallocations)


