--- 
title: set_polygon_info 
format: rst 
date: 2023-01-19 
--- 
# `set_polygon_info`

Set polygon info


## Description

Set giotto polygon spatVector


## Usage

```r
set_polygon_info(gobject, polygon_name = "cell", gpolygon, verbose = TRUE)
```


## Arguments

Argument      |Description
------------- |----------------
`gobject`     |     giotto object
`polygon_name`     |     name of polygons. Default "cell"
`gpolygon`     |     giotto polygon
`verbose`     |     verbosity


## Value

giotto object


## Seealso

Other polygon info data accessor functions:
 [`get_polygon_info`](#getpolygoninfo) 
 
 Other functions to set data in giotto object:
 [`get_cell_id`](#getcellid) ,
 [`get_feat_id`](#getfeatid) ,
 [`set_NearestNetwork`](#setnearestnetwork) ,
 [`set_cell_id`](#setcellid) ,
 [`set_cell_metadata`](#setcellmetadata) ,
 [`set_dimReduction`](#setdimreduction) ,
 [`set_expression_values`](#setexpressionvalues) ,
 [`set_feat_id`](#setfeatid) ,
 [`set_feature_info`](#setfeatureinfo) ,
 [`set_feature_metadata`](#setfeaturemetadata) ,
 [`set_giottoImage`](#setgiottoimage) ,
 [`set_multiomics`](#setmultiomics) ,
 [`set_spatialGrid`](#setspatialgrid) ,
 [`set_spatialNetwork`](#setspatialnetwork) ,
 [`set_spatial_enrichment`](#setspatialenrichment) ,
 [`set_spatial_locations`](#setspatiallocations)


