--- 
title: showGiottoFeatMetadata 
format: rst 
date: 2023-01-19 
--- 
# `showGiottoFeatMetadata`

showGiottoFeatMetadata


## Description

shows the available feature metadata


## Usage

```r
showGiottoFeatMetadata(gobject, nrows = 4)
```


## Arguments

Argument      |Description
------------- |----------------
`gobject`     |     giotto object
`nrows`     |     number of rows to print for each metadata


## Value

prints the name and small subset of available metadata


## Seealso

Other functions to show data in giotto object:
 [`showGiottoCellMetadata`](#showgiottocellmetadata) ,
 [`showGiottoDimRed`](#showgiottodimred) ,
 [`showGiottoExpression`](#showgiottoexpression) ,
 [`showGiottoFeatInfo`](#showgiottofeatinfo) ,
 [`showGiottoImageNames`](#showgiottoimagenames) ,
 [`showGiottoNearestNetworks`](#showgiottonearestnetworks) ,
 [`showGiottoSpatEnrichments`](#showgiottospatenrichments) ,
 [`showGiottoSpatGrids`](#showgiottospatgrids) ,
 [`showGiottoSpatLocs`](#showgiottospatlocs) ,
 [`showGiottoSpatNetworks`](#showgiottospatnetworks) ,
 [`showGiottoSpatialInfo`](#showgiottospatialinfo)


