--- 
title: showGiottoImageNames 
format: rst 
date: 2023-01-19 
--- 
# `showGiottoImageNames`

showGiottoImageNames


## Description

Prints the available giotto images that are attached to the Giotto object


## Usage

```r
showGiottoImageNames(gobject)
```


## Arguments

Argument      |Description
------------- |----------------
`gobject`     |     a giotto object


## Value

prints names of available giotto image objects


## Seealso

Other functions to show data in giotto object:
 [`showGiottoCellMetadata`](#showgiottocellmetadata) ,
 [`showGiottoDimRed`](#showgiottodimred) ,
 [`showGiottoExpression`](#showgiottoexpression) ,
 [`showGiottoFeatInfo`](#showgiottofeatinfo) ,
 [`showGiottoFeatMetadata`](#showgiottofeatmetadata) ,
 [`showGiottoNearestNetworks`](#showgiottonearestnetworks) ,
 [`showGiottoSpatEnrichments`](#showgiottospatenrichments) ,
 [`showGiottoSpatGrids`](#showgiottospatgrids) ,
 [`showGiottoSpatLocs`](#showgiottospatlocs) ,
 [`showGiottoSpatNetworks`](#showgiottospatnetworks) ,
 [`showGiottoSpatialInfo`](#showgiottospatialinfo)


