--- 
title: showGiottoDimRed 
format: rst 
date: 2023-01-19 
--- 
# `showGiottoDimRed`

showGiottoDimRed


## Description

shows the available dimension reductions


## Usage

```r
showGiottoDimRed(gobject, nrows = 3, ncols = 2)
```


## Arguments

Argument      |Description
------------- |----------------
`gobject`     |     giotto object
`nrows`     |     number of coordinates rows to print
`ncols`     |     number of coordinates columns to print


## Value

prints the name and small subset of available dimension reduction coordinates


## Seealso

Other functions to show data in giotto object:
 [`showGiottoCellMetadata`](#showgiottocellmetadata) ,
 [`showGiottoExpression`](#showgiottoexpression) ,
 [`showGiottoFeatInfo`](#showgiottofeatinfo) ,
 [`showGiottoFeatMetadata`](#showgiottofeatmetadata) ,
 [`showGiottoImageNames`](#showgiottoimagenames) ,
 [`showGiottoNearestNetworks`](#showgiottonearestnetworks) ,
 [`showGiottoSpatEnrichments`](#showgiottospatenrichments) ,
 [`showGiottoSpatGrids`](#showgiottospatgrids) ,
 [`showGiottoSpatLocs`](#showgiottospatlocs) ,
 [`showGiottoSpatNetworks`](#showgiottospatnetworks) ,
 [`showGiottoSpatialInfo`](#showgiottospatialinfo)


